apiVersion: kubedb.com/v1alpha1
kind: PerconaXtraDB
metadata:
  name: my-perconaxtradb
#  namespace: demo
spec:
  version: "5.7"
  replicas: 1
#  storageType: Ephemeral
  storageType: Durable
  storage:
    storageClassName: "hostpath"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  updateStrategy:
    type: "RollingUpdate"
  terminationPolicy: WipeOut
