name: rancher-provisioner
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: id;pwd;lsblk;df;cat /proc/mounts

    - name: Create Kubernetes Cluster
      id: buildx
      uses: engineerd/setup-kind@v0.1.0
      with:
        config: hack/github/cluster.yaml

    - name: Install local-path provisioner
      run: |
        export KUBECONFIG="$(kind get kubeconfig-path)"
        kubectl get nodes
        kubectl wait --for=condition=Ready nodes --all --timeout=5m
        kubectl delete storageclass --all
        kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
        # kubectl apply -f ${GITHUB_WORKSPACE}/hack/github/rancher-provisioner.yaml

    - name: Test
      run: |
        echo
        echo ">>> run pod"
        kubectl apply -f ${GITHUB_WORKSPACE}/hack/github/rancher-provisioner-nonroot.yaml
        echo ">>> get pod"
        for i in {1..12}; do kubectl get pod;echo;sleep 5; done
        echo
        echo ">>> get pod"
        kubectl get pod volume-test -o go-template="{{range .status.containerStatuses}}{{.lastState.terminated.message}}{{end}}"
        echo
        echo ">>> describe pod"
        kubectl get pod -n default volume-test -o yaml
        echo
        echo ">>> show pod logs"
        kubectl logs -n default volume-test
        echo
        kubectl get pvc -o yaml
        echo
        kubectl get pv -o yaml
        echo
        kubectl get nodes
